name: tdc3
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - gensim==3.8.0
  - torch==1.9.0
  - libcst==0.3.19
  - matplotlib==3.3.4
  - numpy==1.21.0
  - requests==2.25.1
  - pandas==1.1.5
  - fasttext==0.9.2
  - nltk==3.6.2
  - gdown==3.13.0
  - scikit-learn==0.24.2
  - pydotplus==2.0.2
  - ipython==7.22.0